(function initBeauBirdData(root, factory) {
  const api = factory();
  if (typeof module === "object" && module.exports) {
    module.exports = api;
  } else {
    root.BeauBirdData = api;
  }
})(typeof globalThis !== "undefined" ? globalThis : window, function createBeauBirdData() {
  const birdreportMunicipalityAreas = [
    "湖北省神农架林区",
    "新疆维吾尔自治区北屯市",
    "河南省济源市",
    "海南省五指山市",
    "新疆维吾尔自治区五家渠市",
    "湖北省仙桃市",
    "湖北省潜江市",
    "湖北省天门市",
    "新疆维吾尔自治区石河子市",
    "海南省文昌市",
    "海南省琼海市",
    "海南省东方市",
    "新疆维吾尔自治区可克达拉市",
    "海南省万宁市",
    "海南省乐东黎族自治县",
    "新疆维吾尔自治区双河市",
    "新疆维吾尔自治区图木舒克市",
    "新疆维吾尔自治区昆玉市",
    "新疆维吾尔自治区胡杨河市",
    "新疆维吾尔自治区铁门关市",
    "新疆维吾尔自治区阿拉尔市",
    "海南省临高县",
    "海南省保亭黎族苗族自治县",
    "海南省定安县",
    "海南省屯昌县",
    "海南省昌江黎族自治县",
    "海南省澄迈县",
    "海南省琼中黎族苗族自治县",
    "海南省白沙黎族自治县",
    "海南省陵水黎族自治县",
    "青海省海西蒙古族藏族自治州",
    "台湾省云林县",
    "台湾省南投县",
    "台湾省台东县",
    "台湾省嘉义县",
    "台湾省嘉义市",
    "台湾省基隆市",
    "台湾省宜兰县",
    "台湾省屏东县",
    "台湾省彰化县",
    "台湾省新竹县",
    "台湾省新竹市",
    "台湾省澎湖县",
    "台湾省花莲县",
    "台湾省苗栗县"
  ];

  const traditionalPhraseReplacements = [
    ["臺灣", "台湾"],
    ["鶺鴒", "鹡鸰"],
    ["鸕鶿", "鸬鹚"],
    ["鷦鷯", "鹪鹩"],
    ["鷺鷥", "鹭鸶"]
  ];

  const traditionalCharMap = {
    "萬": "万",
    "東": "东",
    "絲": "丝",
    "個": "个",
    "豐": "丰",
    "麗": "丽",
    "舉": "举",
    "義": "义",
    "烏": "乌",
    "樂": "乐",
    "習": "习",
    "鄉": "乡",
    "書": "书",
    "買": "买",
    "亂": "乱",
    "爭": "争",
    "於": "于",
    "虧": "亏",
    "亞": "亚",
    "產": "产",
    "畝": "亩",
    "親": "亲",
    "褻": "亵",
    "嚴": "严",
    "喪": "丧",
    "豔": "艳",
    "鳳": "凤",
    "麼": "么",
    "廣": "广",
    "門": "门",
    "飛": "飞",
    "馬": "马",
    "魚": "鱼",
    "鳥": "鸟",
    "鳧": "凫",
    "鳩": "鸠",
    "鳶": "鸢",
    "鴉": "鸦",
    "鴒": "鸰",
    "鴕": "鸵",
    "鴛": "鸳",
    "鴞": "鸮",
    "鴝": "鸲",
    "鴣": "鸪",
    "鴦": "鸯",
    "鴨": "鸭",
    "鴯": "鸸",
    "鴴": "鸻",
    "鴿": "鸽",
    "鵂": "鸺",
    "鵑": "鹃",
    "鵒": "鹆",
    "鵓": "鹁",
    "鵜": "鹈",
    "鵐": "鹀",
    "鵝": "鹅",
    "鵠": "鹄",
    "鵡": "鹉",
    "鵪": "鹌",
    "鵯": "鹎",
    "鵰": "雕",
    "鵲": "鹊",
    "鵷": "鹓",
    "鶁": "鹑",
    "鶇": "鸫",
    "鶉": "鹑",
    "鶘": "鹕",
    "鶚": "鹗",
    "鶡": "鹖",
    "鶥": "鹛",
    "鶩": "鹜",
    "鶯": "莺",
    "鶲": "鹟",
    "鶴": "鹤",
    "鶺": "鹡",
    "鶼": "鹣",
    "鶿": "鹚",
    "鷂": "鹞",
    "鷓": "鹧",
    "鷗": "鸥",
    "鷙": "鸷",
    "鷚": "鹨",
    "鷥": "鸶",
    "鷦": "鹪",
    "鷯": "鹩",
    "鷲": "鹫",
    "鷳": "鹇",
    "鷹": "鹰",
    "鷺": "鹭",
    "鸕": "鸬",
    "鸚": "鹦",
    "鸛": "鹳",
    "鸝": "鹂",
    "麥": "麦",
    "黃": "黄",
    "點": "点",
    "龍": "龙",
    "紅": "红",
    "綠": "绿",
    "藍": "蓝",
    "黑": "黑",
    "頭": "头",
    "頸": "颈",
    "頰": "颊",
    "顏": "颜",
    "體": "体",
    "側": "侧",
    "長": "长",
    "腳": "脚",
    "翅": "翅",
    "翹": "翘",
    "線": "线",
    "紋": "纹",
    "斑": "斑",
    "細": "细",
    "闊": "阔",
    "雙": "双",
    "蒼": "苍",
    "臺": "台",
    "灣": "湾",
    "裏": "里",
    "啄": "啄",
    "鸌": "鹱",
    "鸏": "鹲",
    "鷸": "鹬",
    "鱗": "鳞"
  };

  const commonBirdTaxonomy = {
    "白鹭": { sciName: "Egretta garzetta", orderName: "Pelecaniformes", familyName: "Ardeidae", familyCommonName: "鹭", genusName: "Egretta" },
    "苍鹭": { sciName: "Ardea cinerea", orderName: "Pelecaniformes", familyName: "Ardeidae", familyCommonName: "鹭", genusName: "Ardea" },
    "夜鹭": { sciName: "Nycticorax nycticorax", orderName: "Pelecaniformes", familyName: "Ardeidae", familyCommonName: "鹭", genusName: "Nycticorax" },
    "麻雀": { sciName: "Passer montanus", orderName: "Passeriformes", familyName: "Passeridae", familyCommonName: "雀", genusName: "Passer" },
    "乌鸫": { sciName: "Turdus merula", orderName: "Passeriformes", familyName: "Turdidae", familyCommonName: "鸫", genusName: "Turdus" },
    "喜鹊": { sciName: "Pica pica", orderName: "Passeriformes", familyName: "Corvidae", familyCommonName: "鸦", genusName: "Pica" },
    "红嘴蓝鹊": { sciName: "Urocissa erythroryncha", orderName: "Passeriformes", familyName: "Corvidae", familyCommonName: "鸦", genusName: "Urocissa" },
    "戴胜": { sciName: "Upupa epops", orderName: "Bucerotiformes", familyName: "Upupidae", familyCommonName: "戴胜", genusName: "Upupa" },
    "翠鸟": { sciName: "Alcedo atthis", orderName: "Coraciiformes", familyName: "Alcedinidae", familyCommonName: "翠鸟", genusName: "Alcedo" },
    "珠颈斑鸠": { sciName: "Spilopelia chinensis", orderName: "Columbiformes", familyName: "Columbidae", familyCommonName: "鸠鸽", genusName: "Spilopelia" },
    "斑鸠": { sciName: "Streptopelia orientalis", orderName: "Columbiformes", familyName: "Columbidae", familyCommonName: "鸠鸽", genusName: "Streptopelia" },
    "白头鹎": { sciName: "Pycnonotus sinensis", orderName: "Passeriformes", familyName: "Pycnonotidae", familyCommonName: "鹎", genusName: "Pycnonotus" },
    "大山雀": { sciName: "Parus major", orderName: "Passeriformes", familyName: "Paridae", familyCommonName: "山雀", genusName: "Parus" },
    "白鹡鸰": { sciName: "Motacilla alba", orderName: "Passeriformes", familyName: "Motacillidae", familyCommonName: "鹡鸰", genusName: "Motacilla" }
  };

  return {
    birdreportMunicipalityAreas,
    traditionalPhraseReplacements,
    traditionalCharMap,
    commonBirdTaxonomy
  };
});
