import * as config from "./config.js";
import { installStorage } from "./shared/storage.js";
import { installSharedUtils } from "./shared/utils.js";
import { installSharedUi } from "./shared/ui.js";
import { installDownloads } from "./shared/download.js";
import { installRuntime } from "./app/runtime.js";
import { installRecords } from "./features/records.js";
import { installEbirdRecent } from "./features/ebird/recent.js";
import { installEbirdSeasonal } from "./features/ebird/seasonal.js";
import { installBirdreportDomain } from "./features/birdreport/domain.js";
import { installBirdreportClient } from "./features/birdreport/client.js";
import { installBirdreportRegions } from "./features/birdreport/regions.js";
import { installBirdreportQuery } from "./features/birdreport/query.js";
import { installUnlockedSpecies } from "./features/birdreport/unlocked.js";
import { installRareMonitor } from "./features/birdreport/rare-monitor.js";
import { installBirdMap } from "./features/bird-map.js";
import { installBirdPrepMedia } from "./features/bird-prep/media.js";
import { installBirdPrepProfiles } from "./features/bird-prep/profiles.js";
import { installBirdPrepWorkflow } from "./features/bird-prep/workflow.js";
import { installBootstrap } from "./app/bootstrap.js";

const runtime = { ...config };
let stateTarget = null;
let elementsTarget = null;

function createDeferredObjectRef(label, getTarget) {
  return new Proxy({}, {
    get(_target, property) {
      const target = getTarget();
      if (!target) throw new Error(`${label} was accessed before initialization.`);
      return Reflect.get(target, property, target);
    },
    set(_target, property, value) {
      const target = getTarget();
      if (!target) throw new Error(`${label} was mutated before initialization.`);
      return Reflect.set(target, property, value, target);
    },
    has(_target, property) {
      return getTarget() ? property in getTarget() : false;
    },
    ownKeys() {
      return getTarget() ? Reflect.ownKeys(getTarget()) : [];
    },
    getOwnPropertyDescriptor(_target, property) {
      const target = getTarget();
      return target ? Object.getOwnPropertyDescriptor(target, property) : undefined;
    }
  });
}

const stateRef = createDeferredObjectRef("state", () => stateTarget);
const elementsRef = createDeferredObjectRef("elements", () => elementsTarget);
const emptyStateCopyRef = {};
Object.assign(runtime, { state: stateRef, elements: elementsRef, EMPTY_STATE_COPY: emptyStateCopyRef });

installStorage(runtime);
installSharedUtils(runtime);
installSharedUi(runtime);
installDownloads(runtime);
installRuntime(runtime);
installRecords(runtime);
installEbirdRecent(runtime);
installEbirdSeasonal(runtime);
installBirdreportDomain(runtime);
installBirdreportClient(runtime);
installBirdreportRegions(runtime);
installBirdreportQuery(runtime);
installUnlockedSpecies(runtime);
installRareMonitor(runtime);
installBirdMap(runtime);
installBirdPrepMedia(runtime);
installBirdPrepProfiles(runtime);
installBirdPrepWorkflow(runtime);
installBootstrap(runtime);

const { loadPersonalRecords, loadUnlockedSpeciesCache, loadZhejiangRareSpecies, loadZhejiangRareMonitor, loadZhejiangRareNotificationLog } = runtime;
const unlockedSpeciesCache = loadUnlockedSpeciesCache();

const state = {
  personalRecords: loadPersonalRecords(),
  regionQueryRecords: [],
  activeRegionRecordId: null,
  ebirdSeasonalResults: [],
  ebirdSeasonalMeta: null,
  activeEbirdSeasonalSpeciesCode: "",
  birdreportLastQueryPayload: null,
  birdreportLastResults: [],
  activeBirdreportSpeciesKey: null,
  birdreportSpeciesDetailSpecies: null,
  birdreportSpeciesDetailRecords: [],
  birdreportSpeciesDetailLoading: false,
  birdreportSpeciesDetailError: "",
  birdreportSpeciesCaptchaImageUrl: "",
  birdreportSpeciesCaptchaLoading: false,
  birdreportSpeciesCaptchaError: "",
  map: null,
  heatLayer: null,
  expandedTaxa: new Set(),
  migrationSummary: { changed: 0 },
  zhejiangRareSpecies: loadZhejiangRareSpecies(),
  zhejiangRareMonitor: loadZhejiangRareMonitor(),
  zhejiangRareNotificationLog: loadZhejiangRareNotificationLog(),
  zhejiangRareHits: [],
  activeZhejiangRareSpeciesKey: null,
  zhejiangRareSpeciesDetailTargetDate: "",
  zhejiangRareSpeciesDetailSpecies: null,
  zhejiangRareSpeciesDetailRecords: [],
  zhejiangRareSpeciesDetailLoading: false,
  zhejiangRareSpeciesDetailError: "",
  zhejiangRareMonitorTimerId: null,
  zhejiangRareMonitorInFlight: false,
  unlockedSpeciesCatalog: unlockedSpeciesCache.catalog,
  unlockedObservedSpecies: unlockedSpeciesCache.observed,
  unlockedMissingSpecies: unlockedSpeciesCache.missing,
  unlockedTargetUsername: unlockedSpeciesCache.username,
  unlockedSpeciesCacheSavedAt: unlockedSpeciesCache.savedAt,
  unlockedSpeciesShowMeta: false,
  unlockedSpeciesTableVisible: true,
  activeUnlockedSpeciesKey: null,
  unlockedSpeciesDetailRecords: [],
  unlockedSpeciesDetailLoading: false,
  unlockedSpeciesDetailError: "",
  unlockedSpeciesCaptchaImageUrl: "",
  unlockedSpeciesCaptchaLoading: false,
  unlockedSpeciesCaptchaError: "",
  birdPrepLastQueryPayload: null,
  birdPrepSpeciesResults: [],
  birdPrepSelectedSpeciesKeys: new Set(),
  birdPrepUnlockedSpeciesCache: new Map(),
  birdPrepUnlockedFilterUsername: "",
  birdPrepUnlockedFilteredCount: 0,
  birdPrepUnlockedFilterWarning: "",
  birdPrepProfileIndex: null,
  birdPrepProfileIndexLoading: null,
  birdPrepProfileShardIndex: null,
  birdPrepProfileShardIndexLoading: null,
  birdPrepProfileShardProfileCache: new Map(),
  birdPrepProfileShardScriptLoading: new Map(),
  birdPrepMacaulayPhotoCache: new Map(),
  birdPrepMacaulayTaxonomyBySciName: null,
  birdPrepMacaulayTaxonomyLoading: null,
  birdPrepLoading: false,
  birdPrepGenerating: false
};

const elements = {
  fileInput: document.querySelector("#fileInput"),
  pasteInput: document.querySelector("#pasteInput"),
  importPasteBtn: document.querySelector("#importPasteBtn"),
  loadSampleBtn: document.querySelector("#loadSampleBtn"),
  clearAllBtn: document.querySelector("#clearAllBtn"),
  importMessage: document.querySelector("#importMessage"),
  ebirdApiKey: document.querySelector("#ebirdApiKey"),
  ebirdRegionCode: document.querySelector("#ebirdRegionCode"),
  ebirdBackDays: document.querySelector("#ebirdBackDays"),
  syncEbirdBtn: document.querySelector("#syncEbirdBtn"),
  clearEbirdKeyBtn: document.querySelector("#clearEbirdKeyBtn"),
  ebirdMessage: document.querySelector("#ebirdMessage"),
  regionQuerySummary: document.querySelector("#regionQuerySummary"),
  regionQueryContainer: document.querySelector("#regionQueryContainer"),
  regionQueryBackdrop: document.querySelector("#regionQueryBackdrop"),
  regionQueryDetail: document.querySelector("#regionQueryDetail"),
  ebirdSeasonalDate: document.querySelector("#ebirdSeasonalDate"),
  ebirdSeasonalYears: document.querySelector("#ebirdSeasonalYears"),
  ebirdSeasonalWindow: document.querySelector("#ebirdSeasonalWindow"),
  analyzeEbirdSeasonalBtn: document.querySelector("#analyzeEbirdSeasonalBtn"),
  clearEbirdSeasonalCacheBtn: document.querySelector("#clearEbirdSeasonalCacheBtn"),
  ebirdSeasonalMessage: document.querySelector("#ebirdSeasonalMessage"),
  ebirdSeasonalSummary: document.querySelector("#ebirdSeasonalSummary"),
  ebirdSeasonalContainer: document.querySelector("#ebirdSeasonalContainer"),
  birdreportStartDate: document.querySelector("#birdreportStartDate"),
  birdreportEndDate: document.querySelector("#birdreportEndDate"),
  birdreportProvince: document.querySelector("#birdreportProvince"),
  birdreportCity: document.querySelector("#birdreportCity"),
  birdreportDistrict: document.querySelector("#birdreportDistrict"),
  birdreportPointName: document.querySelector("#birdreportPointName"),
  queryBirdreportProxyBtn: document.querySelector("#queryBirdreportProxyBtn"),
  openBirdreportTaxonBtn: document.querySelector("#openBirdreportTaxonBtn"),
  openBirdreportSearchBtn: document.querySelector("#openBirdreportSearchBtn"),
  birdreportMessage: document.querySelector("#birdreportMessage"),
  birdreportSpeciesSummary: document.querySelector("#birdreportSpeciesSummary"),
  birdreportSpeciesContainer: document.querySelector("#birdreportSpeciesContainer"),
  birdreportSpeciesDetailBackdrop: document.querySelector("#birdreportSpeciesDetailBackdrop"),
  birdreportSpeciesDetail: document.querySelector("#birdreportSpeciesDetail"),
  birdPrepProvince: document.querySelector("#birdPrepProvince"),
  birdPrepCity: document.querySelector("#birdPrepCity"),
  birdPrepDistrict: document.querySelector("#birdPrepDistrict"),
  birdPrepPointName: document.querySelector("#birdPrepPointName"),
  birdPrepUnlockedUsername: document.querySelector("#birdPrepUnlockedUsername"),
  birdPrepStartDate: document.querySelector("#birdPrepStartDate"),
  birdPrepEndDate: document.querySelector("#birdPrepEndDate"),
  birdPrepMacaulayImages: document.querySelector("#birdPrepMacaulayImages"),
  birdPrepMacaulayRights: document.querySelector("#birdPrepMacaulayRights"),
  queryBirdPrepSpeciesBtn: document.querySelector("#queryBirdPrepSpeciesBtn"),
  selectAllBirdPrepSpeciesBtn: document.querySelector("#selectAllBirdPrepSpeciesBtn"),
  clearBirdPrepSpeciesBtn: document.querySelector("#clearBirdPrepSpeciesBtn"),
  generateBirdPrepPptBtn: document.querySelector("#generateBirdPrepPptBtn"),
  birdPrepSpeciesSearch: document.querySelector("#birdPrepSpeciesSearch"),
  birdPrepSpeciesOptions: document.querySelector("#birdPrepSpeciesOptions"),
  birdPrepMessage: document.querySelector("#birdPrepMessage"),
  birdPrepProgress: document.querySelector("#birdPrepProgress"),
  birdPrepProgressBar: document.querySelector("#birdPrepProgressBar"),
  birdPrepProgressLabel: document.querySelector("#birdPrepProgressLabel"),
  birdPrepProgressPercent: document.querySelector("#birdPrepProgressPercent"),
  birdPrepProgressDetail: document.querySelector("#birdPrepProgressDetail"),
  birdPrepSummary: document.querySelector("#birdPrepSummary"),
  birdreportUnlockedUsername: document.querySelector("#birdreportUnlockedUsername"),
  queryUnlockedSpeciesBtn: document.querySelector("#queryUnlockedSpeciesBtn"),
  exportUnlockedSpeciesBtn: document.querySelector("#exportUnlockedSpeciesBtn"),
  clearUnlockedSpeciesBtn: document.querySelector("#clearUnlockedSpeciesBtn"),
  unlockedSpeciesMessage: document.querySelector("#unlockedSpeciesMessage"),
  unlockedSpeciesSummary: document.querySelector("#unlockedSpeciesSummary"),
  unlockedSpeciesContainer: document.querySelector("#unlockedSpeciesContainer"),
  saveZhejiangRareSpeciesBtn: document.querySelector("#saveZhejiangRareSpeciesBtn"),
  checkZhejiangRareSpeciesBtn: document.querySelector("#checkZhejiangRareSpeciesBtn"),
  toggleZhejiangRareMonitorBtn: document.querySelector("#toggleZhejiangRareMonitorBtn"),
  zhejiangRareMonitorDate: document.querySelector("#zhejiangRareMonitorDate"),
  zhejiangRareSpeciesMessage: document.querySelector("#zhejiangRareSpeciesMessage"),
  zhejiangRareSpeciesSummary: document.querySelector("#zhejiangRareSpeciesSummary"),
  zhejiangRareSpeciesContainer: document.querySelector("#zhejiangRareSpeciesContainer"),
  zhejiangRareSpeciesDetailBackdrop: document.querySelector("#zhejiangRareSpeciesDetailBackdrop"),
  zhejiangRareSpeciesDetail: document.querySelector("#zhejiangRareSpeciesDetail"),
  speciesFilter: document.querySelector("#speciesFilter"),
  sortOrder: document.querySelector("#sortOrder"),
  viewMode: document.querySelector("#viewMode"),
  lifeRegionFilter: document.querySelector("#lifeRegionFilter"),
  lifeBackDays: document.querySelector("#lifeBackDays"),
  speciesDiscoveryRegion: document.querySelector("#speciesDiscoveryRegion"),
  speciesDiscoveryStart: document.querySelector("#speciesDiscoveryStart"),
  speciesDiscoveryEnd: document.querySelector("#speciesDiscoveryEnd"),
  heatMetric: document.querySelector("#heatMetric"),
  statsSummary: document.querySelector("#statsSummary"),
  taxonomyBrowser: document.querySelector("#taxonomyBrowser"),
  recordsContainer: document.querySelector("#recordsContainer"),
  lifeSummary: document.querySelector("#lifeSummary"),
  lifeListContainer: document.querySelector("#lifeListContainer"),
  speciesDiscoverySummary: document.querySelector("#speciesDiscoverySummary"),
  speciesDiscoveryContainer: document.querySelector("#speciesDiscoveryContainer"),
  calendarLegend: document.querySelector("#calendarLegend"),
  calendarHeatmap: document.querySelector("#calendarHeatmap"),
  birdMapModeControls: document.querySelector("#birdMapModeControls"),
  birdMapDatasetStatus: document.querySelector("#birdMapDatasetStatus"),
  birdMapSpeciesSearch: document.querySelector("#birdMapSpeciesSearch"),
  birdMapSpeciesResults: document.querySelector("#birdMapSpeciesResults"),
  birdMapActiveSpecies: document.querySelector("#birdMapActiveSpecies"),
  birdMapClearSpecies: document.querySelector("#birdMapClearSpecies"),
  birdMapMessage: document.querySelector("#birdMapMessage"),
  birdMapCanvas: document.querySelector("#birdMapCanvas"),
  birdMapCanvasState: document.querySelector("#birdMapCanvasState"),
  birdMapVisibleList: document.querySelector("#birdMapVisibleList"),
  birdMapDetail: document.querySelector("#birdMapDetail")
};

const EMPTY_STATE_COPY = {
  monitor: {
    title: "等待检查稀有鸟种",
    description: "保存基线名单或立即检查所选日期后，命中结果会显示在这里。"
  },
  unlocked: {
    title: "等待查询记录用户",
    description: "输入记录中心用户名后，会显示浙江名录中还未解锁的鸟种。"
  },
  "bird-prep-picker": {
    title: "等待地区鸟种",
    description: "选择地区和日期后查询，再多选要生成 PPT 的鸟种。"
  },
  "ebird-region": {
    title: "等待 eBird 区域记录",
    description: "填入 API Key、区域代码和回溯天数后，最近观测会显示在这里。"
  },
  "ebird-seasonal": {
    title: "等待当季分析",
    description: "选择目标日期并开始分析后，会列出浙江当季候选鸟种。"
  },
  birdreport: {
    title: "等待 BirdReport 查询",
    description: "选择时间和地区后，符合条件的鸟种结果会显示在这里。"
  }
};

stateTarget = state;
elementsTarget = elements;
Object.assign(emptyStateCopyRef, EMPTY_STATE_COPY);
Object.assign(runtime, { state, elements, EMPTY_STATE_COPY });

// Keep every top-level binding from the legacy classic script visible to later
// classic scripts. The manifests intentionally mirror the pre-module script.js
// surface instead of exposing the runtime registry wholesale.
const LEGACY_GLOBAL_DATA_NAMES = Object.freeze([
  "STORAGE_KEY",
  "PERSONAL_STORAGE_KEY",
  "LEGACY_STORAGE_KEY",
  "EBIRD_API_KEY_STORAGE",
  "EBIRD_REGION_STORAGE",
  "EBIRD_BACK_STORAGE",
  "EBIRD_SPECIES_LOCALE",
  "EBIRD_SEASONAL_CACHE_STORAGE",
  "EBIRD_SEASONAL_SETTINGS_STORAGE",
  "EBIRD_SEASONAL_REGION_CODE",
  "EBIRD_SEASONAL_DEFAULT_YEARS",
  "EBIRD_SEASONAL_DEFAULT_WINDOW_DAYS",
  "EBIRD_SEASONAL_CACHE_TTL_MS",
  "EBIRD_SEASONAL_CONCURRENCY",
  "BIRDREPORT_RARE_SPECIES_STORAGE",
  "BIRDREPORT_RARE_MONITOR_STORAGE",
  "BIRDREPORT_RARE_NOTIFICATION_LOG_STORAGE",
  "BIRDREPORT_UNLOCKED_SPECIES_CACHE_STORAGE",
  "BIRDREPORT_SEARCH_PAGE_URL",
  "BIRDREPORT_TAXON_PAGE_URL",
  "BIRDREPORT_ZHEJIANG_SPECIES_DATA_URL",
  "BIRDREPORT_ZHEJIANG_SPECIES_GLOBAL",
  "BIRD_PROFILE_SHARD_BASE_URL",
  "BIRD_PROFILE_SHARD_INDEX_URL",
  "BIRD_PROFILE_SHARD_INDEX_SCRIPT_URL",
  "BIRD_PROFILE_SHARD_INDEX_GLOBAL",
  "BIRD_PROFILE_SHARDS_GLOBAL",
  "ALL_BIRDS_FULL_DATA_URL",
  "ALL_BIRDS_FULL_SCRIPT_URL",
  "ALL_BIRDS_FULL_GLOBAL",
  "BIRD_PREP_LOGIN_EXPIRED_MESSAGE",
  "BIRD_PREP_MACAULAY_MAX_IMAGE_BYTES",
  "BIRD_PREP_MACAULAY_MAX_TOTAL_IMAGE_BYTES",
  "BIRD_PREP_MACAULAY_FETCH_TIMEOUT_MS",
  "BIRD_PREP_MACAULAY_FETCH_ATTEMPTS",
  "BIRD_PREP_IMAGE_DIMENSION_TIMEOUT_MS",
  "BIRDREPORT_CORE",
  "BIRDREPORT_VERSION",
  "ANDROID_APP_USER_AGENT_TOKEN",
  "BIRDREPORT_PARAM_PUBLIC_KEY",
  "BIRDREPORT_AES_KEY_SOURCE",
  "BIRDREPORT_AES_IV_SOURCE",
  "DEFAULT_BIRDREPORT_PROXY_URL",
  "ANDROID_BIRDREPORT_PROXY_URL",
  "BIRDREPORT_RARE_SPECIES_PROVINCE",
  "BIRDREPORT_RARE_SPECIES_THRESHOLD",
  "BIRDREPORT_MONITOR_INTERVAL_MS",
  "UNLOCKED_SPECIES_VISIBLE_ROW_COUNT",
  "BEAUBIRD_UTILS",
  "BEAUBIRD_DATA",
  "formatCompactTimestamp",
  "TRADITIONAL_PHRASE_REPLACEMENTS",
  "TRADITIONAL_CHAR_MAP",
  "COMMON_BIRD_TAXONOMY",
  "SAMPLE_RECORDS",
  "ROOT_CLASS_LABEL",
  "UNKNOWN_ORDER_LABEL",
  "UNKNOWN_FAMILY_LABEL",
  "UNKNOWN_GENUS_LABEL",
  "TAXON_ZH_MAP",
  "unlockedSpeciesCache",
  "state",
  "elements",
  "EMPTY_STATE_COPY"
]);

const LEGACY_GLOBAL_FUNCTION_NAMES = Object.freeze([
  "safeLocalStorageGet",
  "safeLocalStorageSet",
  "safeLocalStorageRemove",
  "bootstrap",
  "bindIfPresent",
  "bindEvents",
  "handleQuickNavClick",
  "markJumpTarget",
  "setActiveQuickNav",
  "initEmbeddedAndroidQuickNav",
  "importText",
  "parseInput",
  "parseJsonInput",
  "parseDelimitedInput",
  "parseLineInput",
  "splitDelimitedLine",
  "toRecord",
  "getRawValue",
  "normalizeHeaderName",
  "normalizeRecords",
  "persistAndRender",
  "render",
  "renderFilters",
  "renderRecordsOnly",
  "renderStats",
  "renderTaxonomyBrowser",
  "renderLifeList",
  "renderSpeciesDiscovery",
  "renderEmptyState",
  "renderRegionQueryResults",
  "renderRegionQueryDetail",
  "closeRegionQueryDetail",
  "handleRegionQueryDetailHotkeys",
  "getVisibleRecords",
  "getLifeListContext",
  "getSpeciesDiscoveryContext",
  "buildSpeciesAggregate",
  "getRecordBoundaryDate",
  "normalizeDateInput",
  "initMap",
  "renderMap",
  "buildHeatPoints",
  "renderCalendarHeatmap",
  "renderLegend",
  "syncEbirdRecords",
  "hydrateEbirdInputs",
  "persistEbirdSettings",
  "clearEbirdApiKey",
  "hydrateEbirdSeasonalInputs",
  "persistEbirdSeasonalSettings",
  "getEbirdSeasonalSettings",
  "analyzeEbirdSeasonalPrediction",
  "renderEbirdSeasonalPrediction",
  "renderEbirdSeasonalDetail",
  "clearEbirdSeasonalCache",
  "fetchEbirdSeasonalDailyEntries",
  "fetchEbirdHistoricSpeciesForDate",
  "fetchEbirdRecentSeasonalObservations",
  "normalizeEbirdSeasonalObservationList",
  "loadEbirdSeasonalCache",
  "saveEbirdSeasonalCache",
  "getCachedEbirdSeasonalDay",
  "setCachedEbirdSeasonalDay",
  "getEbirdSeasonalCacheKey",
  "runLimitedConcurrency",
  "parseIsoDateParts",
  "getEbirdSeasonalCore",
  "formatSeasonalYearRange",
  "formatSeasonalRecentEvidence",
  "getSeasonalProbabilityClass",
  "isEmbeddedAndroidApp",
  "getDefaultBirdreportProxyUrl",
  "applyRuntimeEnvironment",
  "lockEmbeddedAndroidViewport",
  "getBirdreportProxyBaseUrl",
  "hydrateZhejiangRareMonitorInputs",
  "handleZhejiangRareMonitorDateChange",
  "initBirdreportProxy",
  "canUseBirdreportProxy",
  "initZhejiangRareSpeciesMonitor",
  "initZhejiangRareSpeciesDailyQuery",
  "renderZhejiangRareSpeciesPanel",
  "renderZhejiangRareSpeciesHits",
  "saveZhejiangRareSpecies",
  "queryUnlockedSpeciesByUser",
  "fetchZhejiangSpeciesCatalogForUnlocked",
  "fetchUserZhejiangSpecies",
  "buildUnlockedMissingSpecies",
  "sortBirdreportTaxaByReportCountDesc",
  "renderUnlockedSpeciesPanel",
  "renderUnlockedSpeciesSummary",
  "renderUnlockedSpeciesSummaryCard",
  "toggleUnlockedSpeciesInfoVisibility",
  "toggleUnlockedSpeciesTableVisibility",
  "renderUnlockedSpeciesList",
  "createUnlockedSpeciesModuleHeader",
  "buildUnlockedSpeciesMetaLine",
  "renderUnlockedSpeciesLocationPanel",
  "formatUnlockedSpeciesTaxonomy",
  "toggleUnlockedSpeciesLocations",
  "submitUnlockedSpeciesCaptcha",
  "refreshUnlockedSpeciesCaptcha",
  "fetchRecentBirdreportRecordsByTaxon",
  "fetchBirdreportRecordWindowByTaxon",
  "isBirdreportCaptchaResponse",
  "createBirdreportCaptchaError",
  "isBirdreportCaptchaError",
  "loadBirdreportCaptchaImage",
  "verifyBirdreportCaptcha",
  "createBirdreportRecordSearchPayload",
  "clearUnlockedSpeciesDetail",
  "clearUnlockedSpeciesResults",
  "exportUnlockedSpeciesTable",
  "buildUnlockedSpeciesExportRows",
  "buildUnlockedSpeciesExportFilename",
  "toCsvText",
  "escapeCsvField",
  "saveTextFile",
  "triggerFileDownload",
  "toggleZhejiangRareMonitor",
  "startZhejiangRareMonitor",
  "stopZhejiangRareMonitor",
  "scheduleZhejiangRareMonitor",
  "toggleZhejiangRareSpeciesDetail",
  "checkZhejiangRareSpeciesToday",
  "notifyRareSpeciesHits",
  "renderZhejiangRareSpeciesDetail",
  "clearZhejiangRareSpeciesDetail",
  "closeZhejiangRareSpeciesDetail",
  "ensureBrowserNotificationPermission",
  "setZhejiangRareSpeciesLoading",
  "setZhejiangRareSpeciesMessage",
  "setUnlockedSpeciesMessage",
  "updateUnlockedSpeciesExportButton",
  "setUnlockedSpeciesLoading",
  "createBirdreportPayload",
  "getSelectedZhejiangRareMonitorDate",
  "getBirdreportTaxonKey",
  "getBirdreportRarityFields",
  "serializeBirdreportTaxon",
  "getBirdreportTaxaArray",
  "normalizeBirdreportTaxa",
  "fetchZhejiangSpeciesBaselineFromJson",
  "fetchZhejiangSpeciesCatalogFromJson",
  "loadZhejiangSpeciesData",
  "normalizeZhejiangSpeciesCatalog",
  "toRareSpeciesHit",
  "handleBirdreportProvinceChange",
  "handleBirdreportCityChange",
  "loadBirdreportProvinces",
  "handleBirdPrepProvinceChange",
  "handleBirdPrepCityChange",
  "queryBirdPrepSpecies",
  "buildBirdPrepQueryPayload",
  "formatBirdPrepQuerySummary",
  "formatBirdPrepQueryCompleteMessage",
  "getBirdPrepUnlockedUsername",
  "fetchUserNationalBirdPrepSpecies",
  "getBirdPrepUnlockedSpeciesForUser",
  "buildBirdPrepUnlockedTaxonLookup",
  "getBirdPrepTaxonName",
  "filterBirdPrepSpeciesByUnlocked",
  "renderBirdPrepSpeciesOptions",
  "handleBirdPrepSpeciesSelectionChange",
  "formatBirdPrepSpeciesOption",
  "getSelectedBirdPrepSpecies",
  "selectAllVisibleBirdPrepSpecies",
  "clearBirdPrepSpeciesSelection",
  "clearBirdPrepSpeciesResults",
  "generateBirdPrepPpt",
  "shouldUseBirdPrepMacaulayImages",
  "loadBirdPrepMacaulayPhotos",
  "loadBirdPrepMacaulayTaxonomyBySciName",
  "fetchBirdPrepMacaulayPhoto",
  "getBirdPrepMacaulayTaxonCode",
  "getBirdPrepTaxonScientificName",
  "normalizeScientificName",
  "getStoredEbirdApiKey",
  "birdreportProxyGetJson",
  "birdreportProxyGetImage",
  "birdreportProxyGet",
  "fetchWithTimeoutAndRetry",
  "formatFetchTimeoutError",
  "readImageDimensions",
  "getImageExtensionFromContentType",
  "formatBirdPrepMacaulayAttribution",
  "loadBirdPrepProfileIndex",
  "loadBirdPrepProfileIndexForSpecies",
  "loadBirdPrepProfileIndexFromShards",
  "loadBirdPrepProfileShardIndexFromJson",
  "loadBirdPrepProfileShardsFromJson",
  "loadBirdPrepProfileShardIndexFromScript",
  "loadBirdPrepProfileShardsFromScripts",
  "getBirdPrepNeededShardFiles",
  "getBirdPrepProfileIndexFromProfiles",
  "getBirdPrepShardScriptName",
  "assertBirdPrepProfileShardIndex",
  "loadBirdPrepProfileScript",
  "assertBirdPrepProfileResponse",
  "buildBirdPrepProfileIndexFromEmbeddedData",
  "loadBirdPrepEmbeddedDataScript",
  "syncBirdPrepMacaulayOptions",
  "setBirdPrepProgress",
  "resetBirdPrepProgress",
  "yieldToBrowserFrame",
  "setBirdPrepLoading",
  "setBirdPrepGenerating",
  "updateBirdPrepPptButton",
  "queryBirdreportSpeciesByProxy",
  "fetchAllBirdreportTaxa",
  "fetchBirdreportRecordsByTaxon",
  "fetchBirdreportRecordsForCurrentQuery",
  "fetchBirdreportReportPages",
  "fetchBirdreportRecordPages",
  "isPublicBirdreportLocationRecord",
  "normalizeBirdreportTaxonPage",
  "normalizeBirdreportRecordPage",
  "renderBirdreportSpeciesDetail",
  "toggleBirdreportSpeciesDetail",
  "submitBirdreportSpeciesCaptcha",
  "refreshBirdreportSpeciesCaptcha",
  "clearBirdreportSpeciesDetail",
  "closeBirdreportSpeciesDetail",
  "sortBirdreportRecordsByObservationTimeDesc",
  "sortBirdreportRecordsBySerialIdDesc",
  "getBirdreportReportCount",
  "dedupeBirdreportTaxa",
  "sortBirdreportTaxaByRecordCount",
  "sortBirdreportTaxaByRecordCountDesc",
  "birdreportProxyPost",
  "buildBirdreportSignedRequest",
  "serializeBirdreportRequestData",
  "parseBirdreportRequestData",
  "sortBirdreportObjectKeys",
  "generateBirdreportRequestId",
  "renderBirdreportRegionOptions",
  "resetSelectOptions",
  "renderBirdreportSpeciesResults",
  "clearBirdreportSpeciesResults",
  "decodeBirdreportPayload",
  "decodeBirdreportPayloadWithCryptoJs",
  "decodeBirdreportDecimalPairs",
  "setBirdreportLoading",
  "normalizeProxyBaseUrl",
  "openExternalUrl",
  "openBirdreportTaxonPage",
  "openBirdreportSearchPage",
  "buildBirdreportQueryPayload",
  "formatBirdreportQuerySummary",
  "normalizeBirdreportAdministrativeArea",
  "normalizeEbirdObservations",
  "createEbirdObservationId",
  "buildEbirdNotes",
  "fetchEbirdTaxonomyMap",
  "mergeRecords",
  "createDedupKey",
  "normalizeRecord",
  "migrateExistingRecords",
  "countMigratedRecords",
  "buildInitialMessage",
  "getFallbackTaxonomy",
  "buildTaxonomyTree",
  "createTaxonomyNode",
  "hydrateTaxonomyNode",
  "getTaxonomyPath",
  "renderTaxonomyNode",
  "getSortedTaxonomyChildren",
  "formatTaxonLabel",
  "buildCalendarDays",
  "calendarColor",
  "loadPersonalRecords",
  "loadUnlockedSpeciesCache",
  "createEmptyUnlockedSpeciesCache",
  "saveUnlockedSpeciesCache",
  "clearUnlockedSpeciesCache",
  "loadZhejiangRareSpecies",
  "saveZhejiangRareSpeciesToStorage",
  "loadZhejiangRareMonitor",
  "saveZhejiangRareMonitor",
  "loadZhejiangRareNotificationLog",
  "saveZhejiangRareNotificationLog",
  "savePersonalRecords",
  "isLegacyRegionQueryRecord",
  "normalizeDate",
  "formatIsoDate",
  "addDays",
  "formatDate",
  "formatDateTime",
  "formatBirdreportDateTime",
  "toNumber",
  "parsePositiveInteger",
  "toTaxonOrder",
  "createId",
  "extractGenus",
  "simplifyChineseText",
  "chunkArray",
  "clampBackDays",
  "clampEbirdSeasonalYears",
  "clampEbirdSeasonalWindow",
  "setMessage",
  "setEbirdMessage",
  "setEbirdSeasonalMessage",
  "setBirdreportMessage",
  "setBirdPrepMessage",
  "setStatusMessage",
  "setElementLoadingClass",
  "setEbirdLoading",
  "setEbirdSeasonalLoading",
  "escapeHtml",
  "encodeBase64Utf8"
]);

const legacyGlobalData = {
  ...config,
  unlockedSpeciesCache,
  state,
  elements,
  EMPTY_STATE_COPY
};

for (const name of LEGACY_GLOBAL_DATA_NAMES) {
  if (!(name in legacyGlobalData)) {
    throw new Error(`Missing legacy global data binding: ${name}`);
  }
  globalThis[name] = legacyGlobalData[name];
}

for (const name of LEGACY_GLOBAL_FUNCTION_NAMES) {
  const legacyFunction = runtime[name];
  if (typeof legacyFunction !== "function") {
    throw new Error(`Missing legacy global function: ${name}`);
  }
  globalThis[name] = legacyFunction;
}

runtime.bootstrap();
